### ISSUE TITLE
Make BLE.cs generally usable

### ISSUE THREAD

**Issue by adabru** [adabru/BleWinrtDll#3]
It would be nice to have a C# file that can be imported into a Unity project and used as is. My idea is to move the file BLE.cs into the top directory and add the possibility to read the data from a received package.

Other stuff can be added when new feedback comes in.

**Comment by adabru** [comment]
Ok, I guess the UWP provided API is already high-level enough. So one only needs a C# class that defines the marshalling interface to the dll. As such one can use the file [BleApi.cs](https://github.com/adabru/BleWinrtDll/blob/main/BleWinrtDll%20Unity/Assets/BleApi.cs).

**Comment by Joelx** [comment]
Great stuff!!!
