### ISSUE TITLE
Multiple devices support

### ISSUE THREAD

**Issue by tufeixp** [adabru/BleWinrtDll#32]
Does this lib support a multiple devices running?

**Comment by adabru** [comment]
I think yes but I didn't try. See https://github.com/adabru/BleWinrtDll/issues/7#issuecomment-771600983: 
> I guess each bluetooth device normally has a unique device id. In that case you should be able to just call the functions with different device-ids. Each received data-package contains information about the device it was sent from. Likewise, in each data-package you send you can specify the device-id it should go to.

**Comment by tufeixp** [comment]
Yes, I tried and it works~ thanks~

**Comment by mnajib76** [comment]
Hi @tufeixp , can you share your code/project how you read the data when connect to more than 1 device?

**Comment by mnajib76** [comment]
![image](https://user-images.githubusercontent.com/59599733/187335805-9cf2b423-640d-4bc4-9827-7a35091170b6.png)

So based on my understanding we need to SubscribeCharacteristic() for both devices id , services and char id, and all buffer will still pull from the function as in picture above?

**Comment by adabru** [comment]
Hi @mnajib76, you are right. You pull from the function and determine which device it was sent from by inspecting `res.deviceId`. https://github.com/adabru/BleWinrtDll/blob/31fcc9fd733e16a80d712ece893caf0c678f9111/BleWinrtDll/BleWinrtDll.h#L22-L28

**Comment by mnajib76** [comment]
Thank you very much! Manage to do it!
