### ISSUE TITLE
Got error w很

### ISSUE THREAD

**Issue by monkeyfuckeddog** [adabru/BleWinrtDll#35]
![image](https://user-images.githubusercontent.com/13518880/185825612-9cba46f2-8b31-45b2-bc6a-2b4264a20029.png)

How can I fix this?

**Comment by adabru** [comment]
Did you follow the steps in https://github.com/adabru/BleWinrtDll#build?

**Comment by monkeyfuckeddog** [comment]
Got it！

**Comment by adabru** [comment]
Do you still get the error? Did you install the Windows 10 SDK?

**Comment by monkeyfuckeddog** [comment]
Yes,I have win10 sdk. Now I installind win11 SDK, everything is ok now.May be it is because I am in windows11 now.

**Comment by monkeyfuckeddog** [comment]
Same error, after I did somthing, it disappeared.But I do not know why.
