### ISSUE TITLE
How to make it work on Android?

### ISSUE THREAD

**Issue by userqt** [adabru/BleWinrtDll#40]
Hi,

thank you for the great example. I tried it an it works quite well in the editor. I was wondering if this can be made to work for Android and how?

**Comment by adabru** [comment]
Hi @userqt,

this library doesn't work on android. You have to additionally use another library. 

You can check out the asset store: https://assetstore.unity.com/?q=Bluetooth&orderBy=1 . Many of those also work on iOs.

If you want a open source solution you can check out the active project https://github.com/Velorexe/Unity-Android-Bluetooth-Low-Energy or the archived project https://github.com/seiji/unity-bluetooth . That's at least what I found after a google search.

**Comment by userqt** [comment]
Thank you, I will take a look.

**Comment by adabru** [comment]
Actually there is already an issue for android support: https://github.com/adabru/BleWinrtDll/issues/12
So closing this as duplicate. Please feel free to comment on the other issue's thread 👍
